services:
  docking:
    build:
      context: .
      dockerfile: .docker/octane.Dockerfile
    volumes:
      - app_storage:/var/www/html/storage/app
      - ./app:/var/www/html/app
      - ./routes:/var/www/html/routes
    # environment:
    #   DATABASE_URL: 'sqlite:////var/www/html/database/docking.sqlite'
    env_file:
      - .env
    links:
      - gotenberg
    ports:
      - '8888:80'
      - '8080:8080'

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - '9898:3000'

volumes:
  app_storage:
